CC = gcc -Wall

clean:
	rm -f *.o
	rm -f *.a
	rm -f *.so
	rm -f main

run1:
	make clean
	$(CC) main.c -o main
	./main 1

run2:
	make clean
	$(CC) main.c -o main
	./main 2

run3:
	make clean
	$(CC) main.c -o main
	./main 3